[build]
  command = "pnpm install && PLAYWRIGHT_BROWSERS_PATH=./node_modules/playwright/.local-browsers npx playwright install chromium && pnpm build"
  publish = ".next"

[build.environment]
  PLAYWRIGHT_BROWSERS_PATH = "./node_modules/playwright/.local-browsers"

[functions]
  included_files = ["./node_modules/playwright/.local-browsers/**"]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

