[build]
  command = "pnpm install && pnpm build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[functions."scheduled-scrape"]
  schedule = "@hourly"

[[plugins]]
  package = "@netlify/plugin-nextjs"

